# Generated by Django 5.2.11 on 2026-07-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavedjob',
            name='state_id',
        ),
    ]
