# Generated by Django 3.2.25 on 2026-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaque', '0002_remove_usersavedjob_state_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userconfiguration',
            name='choices_use_user_id_bf828e_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersavedjob',
            name='choices_use_user_id_26e842_idx',
        ),
        migrations.AddIndex(
            model_name='userconfiguration',
            index=models.Index(fields=['user', 'group_id'], name='abaque_user_user_id_9c03ab_idx'),
        ),
        migrations.AddIndex(
            model_name='usersavedjob',
            index=models.Index(fields=['user', '-created_at'], name='abaque_user_user_id_6a1cab_idx'),
        ),
    ]
